Import('env', 'arch', 'messaging', 'common', 'visionipc', 'ASIUS_HARDWARE')

libs = [common, messaging, visionipc]
common_srcs = ['cameras/camera_common.cc']
qcom_sensor_srcs = ['sensors/ox03c10.cc', 'sensors/os04c10.cc']
qcom_srcs = ['cameras/camera_qcom2.cc', 'cameras/spectra.cc', 'cameras/cdm.cc'] + common_srcs + qcom_sensor_srcs
asius_srcs = ['cameras/camera_v1.cc', 'sensors/os04c10.cc']

if arch != "Darwin":
  if ASIUS_HARDWARE:
    camera_obj = env.Object(asius_srcs)
    env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)
  else:
    camera_obj = env.Object(qcom_srcs)
    env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)
