import os
Import('env', 'arch', 'messaging', 'common', 'visionipc')

libs = [common, messaging, visionipc]
common_srcs = ['cameras/camera_common.cc']
qcom_sensor_srcs = ['sensors/ox03c10.cc', 'sensors/os04c10.cc']
qcom_srcs = ['cameras/camera_qcom2.cc', 'cameras/spectra.cc', 'cameras/cdm.cc'] + common_srcs + qcom_sensor_srcs
v1_srcs = ['cameras/camera_v1.cc', 'cameras/cdm_v1.cc', 'sensors/os04c10_v1.cc',
            '#openpilot/system/hardware/asius/visionbuf_dma.cc'] + common_srcs

if arch != "Darwin":
  if os.path.isfile("/ASIUS"):
    camera_obj = env.Object(v1_srcs)
    env.Program('camerad_v1', ['main.cc', camera_obj], LIBS=libs)
  else:
    camera_obj = env.Object(qcom_srcs)
    env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)
